name: Cache Relative Path Test

on:
  pull_request:
    branches: [ main ]
    paths: ['packages/auth/**', 'pnpm-lock.yaml']
  workflow_dispatch:

jobs:
  lint:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: ./my-app    

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          always-auth: true
          registry-url: https://registry.npmjs.org
          # TODO: Enable node_modules caching once confirmed that pnpm is working correctly
          # cache: 'npm'


      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 6.32.22

      - run: echo '//registry.npmjs.org/:_authToken=${{ secrets.NPM_INSTALL_TOKEN  }}' > ~/.npmrc

      # - uses: pnpm/action-setup@v2.0.1
      #   name: Install pnpm
      #   id: pnpm-install
      #   with:
      #     version: 6
      #     run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-


      - name: Install dependencies
        working-directory: ./
        run: pnpm i
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_INSTALL_TOKEN}}


